[workspace]
members = [
   "crates/microBioRust",
   "crates/heatmap",
   "crates/seqmetrics", 
   "python/microbiorust-py"]
resolver = "2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

