# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib microbiorustr, .registration = TRUE
NULL

r_molecular_weight <- function(protein_seq) .Call(wrap__r_molecular_weight, protein_seq)

r_hydrophobicity <- function(protein_seq, window_size) .Call(wrap__r_hydrophobicity, protein_seq, window_size)

r_amino_counts <- function(protein_seq) .Call(wrap__r_amino_counts, protein_seq)

r_amino_percentage <- function(protein_seq) .Call(wrap__r_amino_percentage, protein_seq)

r_aromaticity <- function(seq) .Call(wrap__r_aromaticity, seq)

r_instability_index <- function(seq) .Call(wrap__r_instability_index, seq)

# nolint end
